name = "otp-backend"
type = "javascript"
account_id = "<your_cloudflare_account_id>"
workers_dev = true

[vars]
SECRET_KEY = "your_secret_key"
EMAIL_USER = "your_email@gmail.com"
EMAIL_PASSWORD = "your_email_password"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = "465"
